services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGODB_URI: "mongodb://localhost:27017/"
      JWT_SECRET: "LOL"    
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
      MONGO_INITDB_ROOT_USERNAME: "admin" 
      MONGO_INITDB_ROOT_PASSWORD: "admin" 
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db
volumes:
  dbdata:
